# Generated by Django 5.1.4 on 2024-12-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='email_id',
        ),
    ]
